#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < $patch
done

sed -e 's/pam_rhosts//g' -i modules/Makefile.am
export ac_cv_search_crypt=no

autoreconf -sfi
./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var \
    --disable-nls \
    --disable-db

make
make DESTDIR="$1" install

install -Dm644 base-auth.pamd                   "$1/etc/pam.d/base-auth"
install -Dm644 base-account.pamd                "$1/etc/pam.d/base-account"
install -Dm644 base-password.pamd               "$1/etc/pam.d/base-password"
install -Dm644 base-session.pamd                "$1/etc/pam.d/base-session"
install -Dm644 base-session-noninteractive.pamd "$1/etc/pam.d/base-session-noninteractive"
install -Dm644 other.pamd                       "$1/etc/pam.d/other"
install -Dm644 system-local-login.pamd          "$1/etc/pam.d/system-local-login"
install -Dm644 system-login.pamd                "$1/etc/pam.d/system-login"
install -Dm644 su.pamd                          "$1/etc/pam.d/su"
